apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: ssl
        defaultMode: 429
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ['sleep','infinity']
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: '/root/.postgresql'