apiVersion: batch/v1
kind: CronJob
metadata:
  name: clearsessions
spec:
  schedule: "0 0 1 * *"
  startingDeadlineSeconds: 30
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: job
              image: django_app:latest
              imagePullPolicy: IfNotPresent
              command: ["./manage.py", "clearsessions"]
              envFrom:
                - secretRef:
                    name: secret
