apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: django_app:latest
          imagePullPolicy: IfNotPresent
          command: ["./manage.py", "migrate", "--noinput"]
          envFrom:
            - secretRef:
                name: secret